### ISSUE TITLE
My MAX78000 Evaluation Kit doesn't show up as a USB serial port anymore 

### ISSUE THREAD

**Issue by Samotric** [MaximIntegratedAI/MaximAI_Documentation#71] opened 2023-08-02 19:17 UTC
I was originally able to program the board using the Maxim SDK eclipse, but at some point the board stoppped showing in the device manager as a serial port. The board is still programmable but I have no way of seeing the UART results on the serial terminal anymore. I tried unlocking it using the "erase.act" action but that didn't work.

**Comment by Jake-Carter** [comment] 2023-08-07 19:37
Closing as duplicate of https://github.com/Analog-Devices-MSDK/msdk/issues/698, will follow up through that ticket

**Closed by Jake-Carter** 2023-08-07 19:37 UTC
